language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
  
before_script:
  - composer install --prefer-dist
  - mkdir -p build/logs
  
script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 src/ test/
  
after_script:
  - vendor/bin/phpmd src/ text cleancode,codesize,controversial,design,naming,unusedcode
  - vendor/bin/phpmetrics src/
