language: php

php:
  - 5.6
  - 7.0

matrix:
  fast_finish: true
  
before_script:
  - composer install --prefer-dist
  
script:
  - composer test
  - composer style
  
after_script:
  - composer check
  - composer metrics
